version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_DATABASE: MarketPlace
      MYSQL_USER: admin
      MYSQL_PASSWORD: Admin*123
      MYSQL_ROOT_PASSWORD: Admin*123
    ports:
      - 3307:3306
    networks:
      - mynetwork


  backend:
    build: .
    container_name: springboot_app
    depends_on:
      - db
    ports:
      - 8080:8080
    env_file:
      - .env
    restart: always
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge